version: '3'
services:
    openq-api-test:
        container_name: openq-api-test
        build:
            dockerfile: Dockerfile.dev
            context: ./
        env_file:
            - .env
        ports:
            - '5000:5000'
        volumes:
            - /app/node_modules
            - ./OpenQ-API:/app
