version: "1"
services:
  openq-api:
    container_name: openq-api
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./
    ports:
      - "4000:4000"
    volumes:
      - /app/node_modules
      - ./:/app
    env_file:
      - ./.env